# MOL 518 Assignment 1
David Godovich  
06Feb2026

## Problem 1
I used the following websites as references:  
For the [dropcap](https://www.htmldog.com/techniques/dropcaps/) (Including an aside to [this stack overflow page](https://graphicdesign.stackexchange.com/questions/85715/what-is-the-name-of-the-enlarged-and-adorned-first-letter-of-a-book-or-chapter) to find what the textbook fancy first letter is called)  
For the [half width horizontal rule](https://www.w3schools.com/tags/tag_hr.asp)  
For [html colors](https://htmlcolorcodes.com/color-names/)  
And also I know some html

# <font color="steelblue">PREFACE</font>

---

<span style="
float: left;
font-size: 3.5em;
color: steelblue;
line-height: 1;
padding-right: 0.1em;
padding-top: 0.05em;
">T</span>
he more we learn, the more we discover connections threading through our biochemical world. In writing the sixth edition, we have made every effort to present these connections in a way that will help first-time students of biochemistry understand the subject and how very relevant it is to their lives.

<hr style="width:50%;border:1px solid steelblue;margin-left:0">

## <font color="steelblue">Emphasis on Physiological Relevance</font>

Biochemistry is returning to its roots to renew the study of its role in physiology, with the tools of molecular biology and the information gained from gene sequencing in hand. In the sixth edition, we emphasize that an understanding of biochemical pathways is the underpinning for an understanding of physiological systems. Biochemical pathways make more sense to students when they understand how these pathways relate to the physiology of familiar activities such as digestion, respiration, and exercise. In this edition, particularly in the chapters on metabolism, we have taken several steps to ensure that students have a view of the bigger picture:

- Discussions of metabolic regulation emphasize the **everyday conditions** that determine regulation: exercise versus rest; fed versus fasting.
- New **pathway-integration figures** show how multiple pathways work together under a specific condition, such as during a fast.
- More **physiologically relevant examples** have been added throughout the book.

    This physiological perspective is also evident in the new chapter on drug development. The use of a foreign compound to inhibit a specific enzyme sometimes has surprising physiological consequences that reveal new physiological principles.

![StryerPreface_liverketone](./StryerPreface_liverketone-1.png)

# Problem 2

In [8]:
#a
cells = 250000 #(cells)
moi = 1.5 #(dimensionless)
titer = 2e8 #(infectious units per mL)
inoc_vol_ul = 500 #(μL total inoculation volume)

In [9]:
#b
iu_needed = cells*moi
print(iu_needed)

375000.0


MOI (multiplicity of infection) is the number of infectious units per cell 

In [31]:
#c
titer_ul = titer / 1000
print('Titer iu per microliter is', titer_ul)
virus_vol_needed = iu_needed / titer_ul
print('Volume of titer needed:',virus_vol_needed, 'ul')

Titer iu per microliter is 200000.0
Volume of titer needed: 1.875 ul


In [32]:
#d
media_vol = inoc_vol_ul - virus_vol_needed
print('Additional media volume needed:',media_vol,'ul')

Additional media volume needed: 498.125 ul


In [33]:
#e
print(
    f'Cell count: {cells} \nMOI: {moi} \nIU needed: {iu_needed} \nVirus titer volume: {virus_vol_needed} \nAdditional Media Volume:{media_vol}'
)

Cell count: 250000 
MOI: 1.5 
IU needed: 375000.0 
Virus titer volume: 1.875 
Additional Media Volume:498.125


# Problem 3

In [35]:
# !uv pip install numpy #I use uv as a package / environment manager
import numpy as np

Resolved 1 package in 163ms                                          
Installed 1 package in 156ms                                
 + numpy==2.4.2


In [40]:
#a
data = np.loadtxt('growth_curve1.csv',delimiter = ',')

In [41]:
#b
data.shape

(97, 2)

data.shape gives the dimensions of the array in row, column format.

In [47]:
#c
print('first row',data[0,:])
print('last row',data[-1,:])

first row [0.   0.12]
last row [5.76e+04 7.59e-01]


Each row has a time value in the first column and an optical density value in the second column. The first row has time=0 and the last row has time = 57600

In [48]:
#d
time = data[:,0]
od = data[:,1]

In [53]:
#e
sampling_time = int((time[1] - time[0])/60)
print('Sampling Time in minutes:',sampling_time)

Sampling Time in minutes: 10


In [54]:
#f
total_time_days = time[-1]/86400
print('Experiment time in days:',total_time_days)

Experiment time in days: 0.6666666666666666


In [56]:
#g
abs_delta_od = od[-1] - od[0]
fold_delta_od = od[-1]/od[0]

print('Absolute change in optical density:',abs_delta_od)
print('Fold change in optical density:',fold_delta_od)

Absolute change in optical density: 0.639
Fold change in optical density: 6.325


# Problem 4

In [ ]:
import numpy as np

In [59]:
#a
time_hr = np.arange(0,12.25,0.25)
print(time_hr)

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.    2.25  2.5   2.75
  3.    3.25  3.5   3.75  4.    4.25  4.5   4.75  5.    5.25  5.5   5.75
  6.    6.25  6.5   6.75  7.    7.25  7.5   7.75  8.    8.25  8.5   8.75
  9.    9.25  9.5   9.75 10.   10.25 10.5  10.75 11.   11.25 11.5  11.75
 12.  ]


In [60]:
#b
od_0 = 0.08
doubling_time_hr = 1.5

Doubling time is the time for a population of bacteria to double.

In [62]:
#c
od = od_0*(2**(time_hr/doubling_time_hr))
print(od)

[ 0.08        0.08979696  0.10079368  0.11313708  0.12699208  0.14254379
  0.16        0.17959393  0.20158737  0.22627417  0.25398417  0.28508759
  0.32        0.35918786  0.40317474  0.45254834  0.50796834  0.57017518
  0.64        0.71837571  0.80634947  0.90509668  1.01593667  1.14035036
  1.28        1.43675142  1.61269894  1.81019336  2.03187335  2.28070072
  2.56        2.87350284  3.22539789  3.62038672  4.06374669  4.56140144
  5.12        5.74700569  6.45079578  7.24077344  8.12749339  9.12280287
 10.24       11.49401137 12.90159155 14.48154688 16.25498677 18.24560575
 20.48      ]


In [63]:
#d
od_norm = od/od[0]
print(od_norm)

[  1.           1.12246205   1.25992105   1.41421356   1.58740105
   1.78179744   2.           2.2449241    2.5198421    2.82842712
   3.1748021    3.56359487   4.           4.48984819   5.0396842
   5.65685425   6.34960421   7.12718975   8.           8.97969639
  10.0793684   11.3137085   12.69920842  14.25437949  16.
  17.95939277  20.1587368   22.627417    25.39841683  28.50875898
  32.          35.91878555  40.3174736   45.254834    50.79683366
  57.01751796  64.          71.83757109  80.63494719  90.50966799
 101.59366733 114.03503592 128.         143.67514218 161.26989439
 181.01933598 203.18733465 228.07007184 256.        ]


In [68]:
#e
fake_data = np.column_stack((time_hr,od,od_norm))
print(fake_data)
print('fake_data shape:',fake_data.shape)

[[0.00000000e+00 8.00000000e-02 1.00000000e+00]
 [2.50000000e-01 8.97969639e-02 1.12246205e+00]
 [5.00000000e-01 1.00793684e-01 1.25992105e+00]
 [7.50000000e-01 1.13137085e-01 1.41421356e+00]
 [1.00000000e+00 1.26992084e-01 1.58740105e+00]
 [1.25000000e+00 1.42543795e-01 1.78179744e+00]
 [1.50000000e+00 1.60000000e-01 2.00000000e+00]
 [1.75000000e+00 1.79593928e-01 2.24492410e+00]
 [2.00000000e+00 2.01587368e-01 2.51984210e+00]
 [2.25000000e+00 2.26274170e-01 2.82842712e+00]
 [2.50000000e+00 2.53984168e-01 3.17480210e+00]
 [2.75000000e+00 2.85087590e-01 3.56359487e+00]
 [3.00000000e+00 3.20000000e-01 4.00000000e+00]
 [3.25000000e+00 3.59187855e-01 4.48984819e+00]
 [3.50000000e+00 4.03174736e-01 5.03968420e+00]
 [3.75000000e+00 4.52548340e-01 5.65685425e+00]
 [4.00000000e+00 5.07968337e-01 6.34960421e+00]
 [4.25000000e+00 5.70175180e-01 7.12718975e+00]
 [4.50000000e+00 6.40000000e-01 8.00000000e+00]
 [4.75000000e+00 7.18375711e-01 8.97969639e+00]
 [5.00000000e+00 8.06349472e-01 1.007936

In [66]:
#f
np.savetxt('simulated_growth.csv',fake_data, delimiter=',')

In [69]:
#g
data2 = np.loadtxt('simulated_growth.csv',delimiter = ',')
print(data2[:3,:])
print('data2 shape:',data2.shape)

[[0.         0.08       1.        ]
 [0.25       0.08979696 1.12246205]
 [0.5        0.10079368 1.25992105]]
data2 shape: (49, 3)


# Problem 5

In [71]:
#a
samples = [
    "WT_A", "WT_B", "WT_C",
    "KO1_A", "KO1_B", "KO1_C",
    "KO2_A", "KO2_B", "KO2_C",
    "Rescue_A", "Rescue_B", "Rescue_C"
]

In [72]:
#b
print(len(samples))

12


`len(samples)` returns the number of elements in the list `samples`. This is the number of samples in your experiment

In [73]:
#c
samples.append('Blank')
samples.append('PositiveCtrl')
print(samples)

['WT_A', 'WT_B', 'WT_C', 'KO1_A', 'KO1_B', 'KO1_C', 'KO2_A', 'KO2_B', 'KO2_C', 'Rescue_A', 'Rescue_B', 'Rescue_C', 'Blank', 'PositiveCtrl']


In [74]:
#d
samples_sorted = sorted(samples)
print(samples)
print(samples_sorted)

['WT_A', 'WT_B', 'WT_C', 'KO1_A', 'KO1_B', 'KO1_C', 'KO2_A', 'KO2_B', 'KO2_C', 'Rescue_A', 'Rescue_B', 'Rescue_C', 'Blank', 'PositiveCtrl']
['Blank', 'KO1_A', 'KO1_B', 'KO1_C', 'KO2_A', 'KO2_B', 'KO2_C', 'PositiveCtrl', 'Rescue_A', 'Rescue_B', 'Rescue_C', 'WT_A', 'WT_B', 'WT_C']


In [75]:
#e
lane1 = samples_sorted[:5]
lane2 = samples_sorted[5:10]
lane3 = samples_sorted[10:]

In [76]:
#f
print(lane1)
print(lane2)
print(lane3)

['Blank', 'KO1_A', 'KO1_B', 'KO1_C', 'KO2_A']
['KO2_B', 'KO2_C', 'PositiveCtrl', 'Rescue_A', 'Rescue_B']
['Rescue_C', 'WT_A', 'WT_B', 'WT_C']


Slicing is safer than manually retyping as it avoids errors. If the list had 1000 entries, I would quickly write a function to split into whatever number of slices rather than manually selecting the entries. Using `range(0, len(list),int(len(list)/num_splits))` gets equal spacing of slices